---
kind: List
apiVersion: v1
metadata: {}
items:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: web-console-smoke-test-deployment
    labels:
      app: web-console-smoke-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web-console-smoke-test
    template:
      metadata:
        labels:
          app: web-console-smoke-test
      spec:
        containers:
        - name: web-console-smoke-test
          image: benjaminapetersen/web-console-smoke-test:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: CONSOLE_URL
            value: https://192.168.1.69:8443
          - name: TEST_INTERVAL_MINUTES
            value: '2'
          ports:
          - containerPort: 3000
          restartPolicy: Always
- kind: Service
  apiVersion: v1
  metadata:
    name: web-console-smoke-test-service
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: web-console-smoke-test-serving-cert
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 443
      targetPort: 3000
      nodePort: 0
    selector:
      app: web-console-smoke-test
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
