# Prefer the `service.alpha.openshift.io/serving-cert-secret-name` annotation
# on the service instead of manually creating a secret.
#
# If you need to manually create a secret, this file is
# just for reference.  Use the following commands to
# generate the appropriate secret:
#
# ./make_cert.sh
# - this should generate /tls/cert.pem & /tls/key.pem & remove the passphrase
# then, using kubectl or oc:
# kubectl create secret tls --cert ./tls/cert.pem --key ./tls/key.pem -o yaml
# oc create secret tls --cert ./tls/cert.pem --key ./tls/key.pem -o yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: web-console-smoke-test-serving-cert
type: Opaque
data:
  # Do not put actual certificate data here & commit to source control.
  # your secret would not be very secret then, would it?
  #
  # these key names will be the file names if the secret is mounted on disk
  # via a volume mount
  tls.crt: cert goes here!  generate this, don't commit.
  tls.key: cert goes here!  generate this, don't commit.
