apiVersion: v1
kind: Pod
metadata:
  name: web-console-smoke-test-pod
  labels:
    app: web-console-smoke-test
spec:
  restartPolicy: Never
  containers:
  - name: web-console-smoke-test
    image: benjaminapetersen/web-console-smoke-test:latest
    ports:
    - containerPort: 3000
      protocol: TCP
      imagePullPolicy: IfNotPresent
    env:
    # update the IP to <machine-ip>, wherever the console is running
    - name: CONSOLE_URL
      value: https://192.168.1.69:8443
    - name: TEST_INTERVAL_MINUTES
      value: '2'
    volumeMounts:
      - mountPath: /etc/tls-certs
        name: web-console-smoke-test-serving-cert
        readOnly: true
  volumes:
  - name: web-console-smoke-test-serving-cert
    secret:
      defaultMode: 400
      secretName: web-console-smoke-test-serving-cert
