apiVersion: v1
kind: Pod
metadata:
  name: openshift-web-console-smoke-test-pod
  labels:
    app: openshift-web-console-smoke-test
spec:
  restartPolicy: Never
  containers:
  - name: openshift-web-console-smoke-test
    image: benjaminapetersen/openshift-web-console-smoke-test:latest
    ports:
    - containerPort: 3000
      protocol: TCP
    imagePullPolicy: IfNotPresent
    env:
    # update the IP to <machine-ip>, wherever the console is running
    - name: CONSOLE_URL
      value: https://192.168.1.69:8443
    - name: TEST_INTERVAL_MINUTES
      value: '2'
