apiVersion: v1
kind: Pod
metadata:
  name: origin-web-console-smoke-test-pod
  labels:
    app: origin-web-console-smoke-test
  annotations:
    prometheus.io/scrape: "true"
    # todo: enable HTTPS
    prometheus.io/scheme: http
spec:
  restartPolicy: Never
  containers:
  - name: origin-web-console-smoke-test
    image: benjaminapetersen/origin-web-console-smoke-test:latest
    ports:
    - containerPort: 3000
      protocol: TCP
    imagePullPolicy: IfNotPresent
    env:
    # update the IP to <machine-ip>, wherever the console is running
    - name: CONSOLE_URL
      value: https://192.168.1.69:8443
    - name: TEST_INTERVAL
      value: '2'
