apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-console-smoke-test-deployment
  labels:
    app: web-console-smoke-test
spec:
  # replica set
  replicas: 1
  # selector = how the deployment finds pods to manage
  selector:
    matchLabels:
      app: web-console-smoke-test
  template:
    metadata:
      labels:
        app: web-console-smoke-test
    spec:
      containers:
      - name: web-console-smoke-test
        image: benjaminapetersen/web-console-smoke-test:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONSOLE_URL
          value: https://192.168.64.3:8443
        - name: CONSOLE_USER
          value: bob
        - name: CONSOLE_PASSWORD
          value: bob
        - name: TEST_INTERVAL_MINUTES
          value: '2'
        ports:
        - containerPort: 3000
        restartPolicy: Always
        volumeMounts:
          - mountPath: /etc/tls-certs
            name: web-console-smoke-test-serving-cert
            readOnly: true
      volumes:
      - name: web-console-smoke-test-serving-cert
        secret:
          defaultMode: 400
          secretName: web-console-smoke-test-serving-cert
