apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-web-console-smoke-test-deployment
  labels:
    app: openshift-web-console-smoke-test
spec:
  # replica set
  replicas: 1
  # selector = how the deployment finds pods to manage
  selector:
    matchLabels:
      app: openshift-web-console-smoke-test
  template:
    metadata:
      labels:
        app: openshift-web-console-smoke-test
    spec:
      containers:
      - name: openshift-web-console-smoke-test
        image: benjaminapetersen/openshift-web-console-smoke-test:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONSOLE_URL
          value: https://10.192.213.145:8443
        - name: CONSOLE_USER
          value: bob
        - name: CONSOLE_PASSWORD
          value: bob
        - name: TEST_INTERVAL_MINUTES
          value: '2'
        ports:
        - containerPort: 3000
        restartPolicy: Always
