apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-protractor
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: run-protractor
          labels:
            app: origin-web-console-smoke-test
        spec:
          containers:
          - name: run-protractor
            image: byrnedo/alpine-curl
            # The IP needs to be updated based on the origin-web-console-smoke-test-service IP address that in front of origin-web-console-smoke-test-pod
            command: ["/bin/sh",  "-c", "curl -k 172.30.136.123:3000/protractor"]
          restartPolicy: Never
