apiVersion: v1
kind: Service
metadata:
  name: web-console-smoke-test-service
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: web-console-smoke-test-serving-cert
      # TODO:
      # don't we need these annotations, just like the web-console?
      # https://github.com/openshift/origin/blob/master/install/origin-web-console/console-template.yaml#L127
      # prometheus.io/scrape: "true"
      # prometheus.io/scheme: https
spec:
  ports:
  - name: web
    protocol: TCP
    port: 443
    targetPort: 3000
    nodePort: 0
  selector:
    app: web-console-smoke-test
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
