kind: Service
apiVersion: v1
metadata:
  name: origin-web-console-smoke-test-service
spec:
  ports:
  - name: web
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 0
  selector:
    app: origin-web-console-smoke-test
  type: ClusterIP
  # This IP is just for dev purposes. In prod. cluster the IP is likely to be reserved or taken.  
  clusterIP: 172.30.136.123
  sessionAffinity: None
status:
  loadBalancer: {}